### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by sbrl** [ogewan/direction.js#1]
Adding a demo to this project (perhaps using github pages) would allow people to see that this library can to before they use it for themselves. That way they can tell if the library fits their requirements.

**Comment by ogewan** [comment]
Direction.js was made with [comix-ngn](http://comixngn.js.org/) in mind, so I forgot to include a demo for direction.js, since [comix-ngn](http://comixngn.js.org/)'s demos use direction.js. However, I'll add a page w/ demo as you suggest.

**Comment by sbrl** [comment]
Cool! Thanks :)

**Comment by ogewan** [comment]
Alright added a demo page at http://seun40.github.io/direction.js/, I will probably add controls later on.

**Comment by sbrl** [comment]
Awesome, thanks!
